[package]
name = "lorawan-device"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
defmt = { version = "0.2.0", optional = true }
embedded-hal = "0.2.6"
radio = { git = "https://github.com/rust-iot/radio-hal.git", rev = "4d4ec82" }

[features]
ttn = []

defmt-default = ["defmt"]
defmt-trace = ["defmt"]
defmt-debug = ["defmt"]
defmt-info = ["defmt"]
defmt-warn = ["defmt"]
defmt-error = ["defmt"]
